---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: nri-plugins
    repo_url: "https://containers.github.io/nri-plugins"

- name: Deploy nri-resource-policy-topology-aware plugin
  kubernetes.core.helm:
    name: topology-aware
    chart_ref: nri-plugins/nri-resource-policy-topology-aware
    release_namespace:  "{{ pluginNamespace }}"
    chart_version: "{{ pluginVersion }}"
    values_files: "{{ pluginValuesFile }}"
    wait: True
    create_namespace: True
  when: pluginName == "topology-aware"

- name: Deploy nri-resource-policy-balloons plugin
  kubernetes.core.helm:
    name: balloons
    chart_ref: nri-plugins/nri-resource-policy-balloons
    release_namespace:  "{{ pluginNamespace }}"
    chart_version: "{{ pluginVersion }}"
    values_files: "{{ pluginValuesFile }}"
    wait: True
    create_namespace: True
  when: pluginName == "balloons"

- name: Deploy nri-memory-qos plugin
  kubernetes.core.helm:
    name: memory-qos
    chart_ref: nri-plugins/nri-memory-qos
    release_namespace:  "{{ pluginNamespace }}"
    chart_version: "{{ pluginVersion }}"
    values_files: "{{ pluginValuesFile }}"
    wait: True
    create_namespace: True
  when: pluginName == "memory-qos"

- name: Deploy nri-memtierd plugin
  kubernetes.core.helm:
    name: memtierd
    chart_ref: nri-plugins/nri-memtierd
    release_namespace:  "{{ pluginNamespace }}"
    chart_version: "{{ pluginVersion }}"
    values_files: "{{ pluginValuesFile }}"
    wait: True
    create_namespace: True
  when: pluginName == "memtierd"
